title: DB's Real-Time Thought Stream
description: > # this means to ignore newlines until "baseurl:"
  Just my unfiltered real-time thoughts on tweets, blog posts, articles, charts, and just general thoughts I have throughout the day. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: dbh.eth # add your name
author-img: dbh.png # add your photo
about-author: These are my raw and unfiltered thoughts on tweets, blog articles, headline news, trading markets and everything else. # add description
social-twitter: dbhurley # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: dbhurley # add your Github handle
social-linkedin: dbhurley # add your Linkedin handle
social-email: dbhurley@me.com # add your Email address

# Disqus
# discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
